language: node_js

node_js:
  - 0.12
  
env:
    global:
        - GIT_NAME=ange007
        - GIT_EMAIL=ange007@users.noreply.github.com
        - GIT_DOMAIN=github.com

#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g gulp
  - DIST_PATH=$TRAVIS_BUILD_DIR/demo
  - REPO_URL=https://$OAuth@$GIT_DOMAIN/$TRAVIS_REPO_SLUG.git
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"

script: 
  - gulp clean && gulp build
  - gulp build:min

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      cd $DIST_PATH;
      git clone $REPO_URL dist;
      cd $DIST_PATH && git checkout gh-pages && rm -rf *;
      cd $TRAVIS_BUILD_DIR && npm run build;
      cd $DIST_PATH && git add -A && git commit -am "Travis build $TRAVIS_BUILD_NUMBER";
      git push $REPO_URL gh-pages;
    fi

#after_script:    

deploy:
  provider: releases
  api_key: $OAuth
  file:
    - $TRAVIS_BUILD_DIR/build/jquery.formStylerModern.js
    - $TRAVIS_BUILD_DIR/build/jquery.formStylerModern.css
    - $TRAVIS_BUILD_DIR/build/jquery.formStylerModern.min.js
    - $TRAVIS_BUILD_DIR/build/jquery.formStylerModern.css
  skip_cleanup: true
  on:
    repo: ange007/JQueryFormStyler-Modern
    #branch: master
    tags: true

sudo: false

cache:
  directories:
    - node_modules