language: node_js
node_js:
  - 0.12
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp
script: 
  - gulp clean && gulp build
  - gulp build:min
#after_script:
deploy:
  provider: releases
  api_key: $OAuth
  file:
    - $JS
    - $CSS
    - $JS:min
    - $CSS:min
  skip_cleanup: true
  on:
    repo: ange007/JQueryFormStyler-Modern
    #branch: master
    tags: true
sudo: false
cache:
  directories:
    - node_modules